// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jhegwcdmxfztakriuyxw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpoZWd3Y2RteGZ6dGFrcml1eXh3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczNzc0OTUsImV4cCI6MjA2Mjk1MzQ5NX0.jKFkY0_Kh3wQrFDQqTVVpsDtC9aMel3-tsWe3oMzqJA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);